### ISSUE TITLE
device kernel panicking

### ISSUE THREAD

**Issue by Allanrfox** [dualra1n/dualra1n#101]
Last login: Sat Jul 13 17:45:02 on console
allanfoxdiaz@MacBook-Pro-de-Allan ~ % cd dualra1n
allanfoxdiaz@MacBook-Pro-de-Allan dualra1n % ./dualboot.sh --downgrade iPadOS 14.8
[*] Command ran: ./dualboot.sh --downgrade
[-] No version specified for pyimg4 and it is not installed. Installing the latest version.
Defaulting to user installation because normal site-packages is not writeable
Collecting pyimg4
  Downloading pyimg4-0.8.5-py3-none-any.whl (15 kB)
Collecting click<9.0.0,>=8.1.7
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
Collecting asn1<3.0.0,>=2.7.0
  Downloading asn1-2.7.0-py2.py3-none-any.whl (10 kB)
Collecting apple-compress<0.3.0,>=0.2.3
  Downloading apple_compress-0.2.3-py3-none-any.whl (6.2 kB)
Collecting pycryptodome<4.0.0,>=3.18.0
  Downloading pycryptodome-3.20.0-cp35-abi3-macosx_10_9_x86_64.whl (1.6 MB)
Collecting pylzss<0.4.0,>=0.3.7
  Downloading pylzss-0.3.8-cp39-cp39-macosx_10_9_x86_64.whl (28 kB)
Collecting loguru<0.8.0,>=0.7.2
  Downloading loguru-0.7.2-py3-none-any.whl (62 kB)
Collecting enum-compat
  Downloading enum_compat-0.0.3-py3-none-any.whl (1.3 kB)
Installing collected packages: loguru, enum-compat, click, pylzss, pycryptodome, asn1, apple-compress, pyimg4
  WARNING: The script acompress is installed in '/Users/allanfoxdiaz/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pyimg4 is installed in '/Users/allanfoxdiaz/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed apple-compress-0.2.3 asn1-2.7.0 click-8.1.7 enum-compat-0.0.3 loguru-0.7.2 pycryptodome-3.20.0 pyimg4-0.8.5 pylzss-0.3.8
WARNING: You are using pip version 21.2.4; however, version 24.1.2 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
[+] lzss is already installed.
[-] No version specified for pyliblzfse and it is not installed. Installing the latest version.
Defaulting to user installation because normal site-packages is not writeable
Collecting pyliblzfse
  Downloading pyliblzfse-0.4.1-cp39-cp39-macosx_10_9_x86_64.whl (23 kB)
Installing collected packages: pyliblzfse
Successfully installed pyliblzfse-0.4.1
WARNING: You are using pip version 21.2.4; however, version 24.1.2 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
dualboot | Version: 8.5
Created by edwin :) | Some functions code from palera1n.sh, Thanks Nathan for the ramdisks | thanks MatthewPierson, Ralph0045, and to all of the creaters of path file boot

[*] Looking for devices
[*] Detected DFU mode device
[*] Getting your device info...
[*] Detected cpid, your cpid is 0x7000
[*] Detected model, your model is j96ap
[*] Detected deviceid, your deviceid is iPad5,1
[?] Found matching IPSW: ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
[?] Do you want to use it? Please write 'yes' or 'no'
Yes
[*] Selected IPSW: ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
Choose an IPSW by entering its number:
1. ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
Enter your choice: 1
[*] We are gonna use ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
[*] Checking if the ipsw is for your device
[*] Checking ipsw version
[*] Extracting ipsw, this could take a while...
Archive:  ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
[*] Creating the ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting the ramdisk
[/] We couldn't get the ipsw curl. we will proceed with -k option with curl
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0002702111910026 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0002702111910026 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0002702111910026 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0002702111910026 IBFL:1C SRTG:[iBoot-1992.0.0.1.19] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Waiting for the ramdisk to finish booting
[!] It looks like ssh is not working, please try to reboot your computer or send the log through discord
Press [ENTER] to continue
^C
allanfoxdiaz@MacBook-Pro-de-Allan dualra1n % ./dualboot.sh --dualboot iPadOS 14.8
[*] Command ran: ./dualboot.sh --dualboot
[+] Found installed version of pyimg4: 0.8.5
[+] pyimg4 is already installed with version 0.8.5.
[+] lzss is already installed.
[+] Found installed version of pyliblzfse: 0.4.1
[+] pyliblzfse is already installed with version 0.4.1.
dualboot | Version: 8.5
Created by edwin :) | Some functions code from palera1n.sh, Thanks Nathan for the ramdisks | thanks MatthewPierson, Ralph0045, and to all of the creaters of path file boot

[*] Looking for devices
[*] Detected DFU mode device
[*] Getting your device info...
[*] Detected cpid, your cpid is 0x7000
[*] Detected model, your model is j96ap
[*] Detected deviceid, your deviceid is iPad5,1
[?] Found matching IPSW: ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
[?] Do you want to use it? Please write 'yes' or 'no'
yes
[*] Selected IPSW: ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
[*] Checking if the ipsw is for your device
[*] Checking ipsw version
[*] Extracting ipsw, this could take a while...
Archive:  ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
[*] Creating the ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting the ramdisk
[/] We couldn't get the ipsw curl. we will proceed with -k option with curl
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0002702111910026 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0002702111910026 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0002702111910026 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0002702111910026 IBFL:1C SRTG:[iBoot-1992.0.0.1.19] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
bind(): Address already in use
Error creating socket for listen port 2222: Address already in use
[*] Waiting for the ramdisk to finish booting
dual[!] It looks like ssh is not working, please try to reboot your computer or send the log through discord
Press [ENTER] to continue

brand new install of macOS Monterey, I'm downgrading /dualbooting an iPad mini 4 128gb on iOS 15.7.8

my device on the other hand every single time it boots to the Ramdisk, it kernel panics, IDK why,

![IMG_1089](https://github.com/user-attachments/assets/e4ef3d53-1097-46ae-accd-60ed30242d04)

**Comment by edwin170** [comment]
this was fixed by rm -rfv ramdisk/boot and trying dualra1n again
