### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [dualra1n/dualra1n#105]
Dear @dualra1n team, @edwin170,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by dualra1n** [comment]
Thx

**Comment by Neustradamus** [comment]
@edwin170: It has been not done, can you reopen it?

Thanks in advance.

**Comment by edwin170** [comment]
> @edwin170: It has been not done, can you reopen it?
> 
> 
> 
> Thanks in advance.


Thank you so much for it, I did wanted to make it an organization however no one else will be working on it, if I knew someone else that is helping and improving dualra1n I would be happy to make an organization and add people to improve it but I know there is noone sadly, also dualra1n won't be updated anymore, maybe just to fix some link needed or info needed but not more. Btw thank you so much for your tutorial ❤️

**Comment by Neustradamus** [comment]
@edwin170: Alone or several people it is important to have an organization for this project.
Your personal account is edwin170.

**Comment by edwin170** [comment]
> @edwin170: Alone or several people it is important to have an organization for this project.
> 
> Your personal account is edwin170.


Mmh okey, I'll do it probably in the future I will need a organization and how to crate it.

**Comment by edwin170** [comment]
> Dear @dualra1n team, @edwin170,
> 
> It is possible to migrate the personal account to organization?
> 
> Converting:
> 
> * https://help.github.com/articles/converting-a-user-into-an-organization/
> 
> It is possible to rename this account and create the organization and move/transfer the repository to the organization.
> 
> Rename account:
> 
> * https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username
> 
> Create an organization:
> 
> * https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch
> 
> Transfer a repository:
> 
> * https://help.github.com/en/github/administering-a-repository/transferring-a-repository
> 
> Like:
> 
> * [http://github.com/gnome](https://github.com/gnome)
> * [http://github.com/kde](https://github.com/kde)
> * ...

i just read it and that's too much to do to convert it an organization, i think it's not worth it to do it, i just let it like that

**Comment by edwin170** [comment]
however thank you for your recommendation

**Comment by Neustradamus** [comment]
@edwin170: Convertion is easy, I can do it in few seconds:
- https://docs.github.com/fr/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/converting-a-user-into-an-organization#convert-your-personal-account-into-an-organization-automatically

You have already your personal account.

**Comment by dualra1n** [comment]
> @edwin170: Convertion is easy, I can do it in few seconds:
> 
> * https://docs.github.com/fr/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/converting-a-user-into-an-organization#convert-your-personal-account-into-an-organization-automatically
> 
> You have already your personal account.

You cannot transform this account into an organization because you have an active GitHub Sponsors account.


whattt! i don't have Sponsors iirc

**Comment by dualra1n** [comment]
lol i even didn't remember that i applied to be a sponsor but it is pending since 1 year i think

**Comment by Neustradamus** [comment]
@dualra1n: Please do it and it will be perfect after:
- https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/disabling-your-github-sponsors-account

**Comment by Neustradamus** [comment]
@dualra1n, @edwin170: Can you do it to be perfect?

1/ https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/disabling-your-github-sponsors-account

2/ https://docs.github.com/fr/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/converting-a-user-into-an-organization#convert-your-personal-account-into-an-organization-automatically

Thanks in advance.

**Comment by edwin170** [comment]
> @dualra1n, @edwin170: Can you do it to be perfect?
> 
> 
> 
> 1/ https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/disabling-your-github-sponsors-account
> 
> 
> 
> 2/ https://docs.github.com/fr/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/converting-a-user-into-an-organization#convert-your-personal-account-into-an-organization-automatically
> 
> 
> 
> Thanks in advance.

Thank you but I tried and I must do something different, I need to give information etc etc, soo thank you but I won't do it for now

**Comment by Neustradamus** [comment]
@edwin170: What informations?

Can you reopen this ticket before the resolution?

Can you give me your e-mail address, I will send you an e-mail and I can do easily few steps, for the project, it is important.

**Comment by Neustradamus** [comment]
@edwin170: What informations?

Can you reopen this ticket before the resolution?

Can you give me your e-mail address, I will send you an e-mail and I can do easily few steps, for the project, it is important.

**Comment by dualra1n** [comment]
> @edwin170: What informations?
> 
> Can you reopen this ticket before the resolution?
> 
> Can you give me your e-mail address, I will send you an e-mail and I can do easily few steps, for the project, it is important.

![sponsor](https://github.com/user-attachments/assets/724350d7-09f8-401f-be0c-dcdc242427d6)

damn, when i try to finish it it needs some info, i am not gonna do that shit i give up bro, btw thank you for teach me it

**Comment by Neustradamus** [comment]
@dualra1n: To leave Sponsor, please read steps here:
- https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/disabling-your-github-sponsors-account

**Comment by Neustradamus** [comment]
@dualra1n: To leave Sponsor, please read steps here:
- https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/disabling-your-github-sponsors-account

**Comment by Neustradamus** [comment]
@dualra1n, @dualra1n: Have you progressed?

**Comment by Neustradamus** [comment]
@dualra1n, @edwin170: Have you progressed?

**Comment by edwin170** [comment]
> @dualra1n, @edwin170: Have you progressed?

not yet
