### ISSUE TITLE
./dualboot.sh: line 906: [: too many arguments

### ISSUE THREAD

**Issue by aditya11110** [dualra1n/dualra1n#16]
iphone x 10,6 (ios 15.6 rc

ubuntu 

getting error ./dualboot.sh: line 906: [: too many arguments

**Comment by edwin170** [comment]
> iphone x 10,6 (ios 15.6 rc
> 
> ubuntu
> 
> getting error ./dualboot.sh: line 906: [: too many arguments

some times if the script doesn't stop that is not a error. if the script stop that means it is error

**Comment by edwin170** [comment]
> iphone x 10,6 (ios 15.6 rc
> 
> ubuntu
> 
> getting error ./dualboot.sh: line 906: [: too many arguments

also that it is normal 
that is not a error just let it continue
