### ISSUE TITLE
my iphone 10,4 (iphone 8) boots into a black screen

### ISSUE THREAD

**Issue by Rubanoxd** [dualra1n/dualra1n#18]
im attemping to dualboot 14.3 from 15.6RC, everything goes well, but it doesnt boot properly. thanks in advance 

btw, the discord link is broken 

![Captura de pantalla 2023-02-21 a les 21 09 08](https://user-images.githubusercontent.com/79226094/220447728-20dc8368-e4c3-4ce4-ae9f-7622f0109ea6.png)
![IMG_0005](https://user-images.githubusercontent.com/79226094/220448049-2ceccb4c-4761-4a89-8ed7-b788b0ec09d3.jpeg)

**Comment by The1Day** [comment]
iPhone 6s Plus (8,2) 15.7.3 -> 14.8 same history here - V.1.0 of script from GitHub archive is working fine

**Comment by dualra1n** [comment]
> im attemping to dualboot 14.3 from 15.6RC, everything goes well, but it doesnt boot properly. thanks in advance
> 
> btw, the discord link is broken
> 
> ![Captura de pantalla 2023-02-21 a les 21 09 08](https://user-images.githubusercontent.com/79226094/220447728-20dc8368-e4c3-4ce4-ae9f-7622f0109ea6.png) ![IMG_0005](https://user-images.githubusercontent.com/79226094/220448049-2ceccb4c-4761-4a89-8ed7-b788b0ec09d3.jpeg)

hi thanks so much for the discord link, sorry because i add a bad option so i fixed just git pull and execute ./dualboot.sh --dualboot 14.3 --dont_createPart (putting --dont_createPart in order to just create the boot files again  ) after that your device will boot into ios 14.3

**Comment by dualra1n** [comment]
> oes well, but it doesnt boot properly

did the iphone show a verbose boot the first time and after the black screen ?

**Comment by dualra1n** [comment]
> iPhone 6s Plus (8,2) 15.7.3 -> 14.8 (14.2, 14.3) same history here - V.1.0 of script from GitHub archive is working fine

I fixed it, thank you for reporting it

**Comment by Rubanoxd** [comment]
> > oes well, but it doesnt boot properly
> 
> did the iphone show a verbose boot the first time and after the black screen ?
>  

It does show a verbose boot

**Comment by dualra1n** [comment]
> > > oes well, but it doesnt boot properly
> > 
> > 
> > did the iphone show a verbose boot the first time and after the black screen ?
> 
> It does show a verbose boot, then it stays on a black screen

ios 14.2 below doesnt work on iphone 8 so use 14.3 above
