### ISSUE TITLE
iPhone 6s Plus (8,2) 14.8 Sileo/Zebra Pogo Jailbreak not signing to repos stores

### ISSUE THREAD

**Issue by The1Day** [dualra1n/dualra1n#19]
Sign window in Sileo/Zebra to the store is not popuping when pressed on the repo name no matter what tweaks are installed. Tested also on Sileo Nightly for XinaA15 https://github.com/Sileo/Sileo but with no result.

https://user-images.githubusercontent.com/74194283/221408742-6efdc06a-a22b-4e4e-b347-ddaaffc47c8a.MP4

**Comment by dualra1n** [comment]
> Sign window in Sileo/Zebra to the store is not popuping when pressed on the repo name no matter what tweaks are installed. Tested also on Sileo Nightly for XinaA15 https://github.com/Sileo/Sileo but with no result.

what ios did you dualboot?, thats the jailbreak pogo right ?

**Comment by The1Day** [comment]
> > Sign window in Sileo/Zebra to the store is not popuping when pressed on the repo name no matter what tweaks are installed. Tested also on Sileo Nightly for XinaA15 https://github.com/Sileo/Sileo but with no result.
> 
> what ios did you dualboot?, thats the jailbreak pogo right ?

Dualbooting iOS 14.8, Pogo, yes. Is this fixed?

**Comment by dualra1n** [comment]
> > > Sign window in Sileo/Zebra to the store is not popuping when pressed on the repo name no matter what tweaks are installed. Tested also on Sileo Nightly for XinaA15 https://github.com/Sileo/Sileo but with no result.
> > 
> > 
> > what ios did you dualboot?, thats the jailbreak pogo right ?
> 
> Dualbooting iOS 14.8, Pogo, yes. Is this fixed?

ahhhh i have never seen that error so i think nop
