### ISSUE TITLE
full tutorial here

### ISSUE THREAD

**Issue by aditya11110** [dualra1n/dualra1n#20]
Please add this link

https://youtu.be/SPu5ljxxXvs

you can watch this is a guide for dualra1n properly for linux 

please add it in the guide

**Comment by dualra1n** [comment]
> Please add this link
> 
> https://youtu.be/SPu5ljxxXvs
> 
> you can watch this is a guide for dualra1n properly for linux
> 
> please add it in the guide

oh thank you so much bro, however, i already have one video to add to the readme.md. thank you so much.

**Comment by aditya11110** [comment]
And having a issue while jailbreaking with taurine 14.2 when jb is done it shows it will reboot but after booting in 14.2 i cant see taurine ??? What is the issue

**Comment by dualra1n** [comment]
> Means u will not add it? Please add it at main page please pray

sorry bro, i already have one video soon bro tysm

**Comment by dualra1n** [comment]
> And having a issue while jailbreaking with taurine 14.2 when jb is done it shows it will reboot but after booting in 14.2 i cant see taurine ??? What is the issue

if you see sileo doesnt matter, just use sileo and install the tweaks that you want

**Comment by aditya11110** [comment]
Sileo is also not appearing

**Comment by dualra1n** [comment]
> Sileo is also not appearing

mmm so do it, just --jailbreak 14.2, to install pogo jailbreak

**Comment by aditya11110** [comment]
You should have said it before that you dont want to add my video ,just bcz my subscribers are low ,

**Comment by wanqfx** [comment]
``rsep nonce（20字节）：1743804bcffcfd069725a3c904bc30c77ac97d70与本地主机的连接被远程主机关闭。[-] 发生错误[*]已制作失败日志。如果您要寻求帮助，请附上最`host.`降级13.7时卡住了

**Comment by dualra1n** [comment]
> You should have said it before that you dont want to add my video ,just bcz my subscribers are low ,

bro, it's not for that reason, i had spoken with a person on youtube and he told me that he will update a video first than you. bro your video is very good, ty

**Comment by dualra1n** [comment]
> ``rsep nonce（20字节）：1743804bcffcfd069725a3c904bc30c77ac97d70与本地主机的连接被远程主机关闭。[-] 发生错误[*]已制作失败日志。如果您要寻求帮助，请附上最`host.`降级13.7时卡住了

ios 16 are not supported

**Comment by wanqfx** [comment]
> > ``rsep nonce（20字节）：1743804bcffcfd069725a3c904bc30c77ac97d70与本地主机的连接被远程主机关闭。[-] 发生错误[*]已制作日志失败。如果您要寻求帮助，请附上最`host.`降级13.7时卡住了>> ios 16不受支持是ios14.4.2啊
