### ISSUE TITLE
./dualboot.sh: line 1027: 3343 Segmentation fault: 11 "$dir"/tree patcher work/dtree.raw work/dtree.patched -d -p

### ISSUE THREAD

**Issue by Cole2024** [dualra1n/dualra1n#25]
Getting stuck on this error trying to dual boot iOS 13.7 and the latest version of iOS 15. I have a A9 device.

**Comment by dualra1n** [comment]
> Getting stuck on this error trying to dual boot iOS 13.7 and the latest version of iOS 15. I have a A9 device.

you didn't specify the version, for example, you have to use it like this. ./dualboot.sh --dualboot 13.7

**Comment by dualra1n** [comment]
> > Getting stuck on this error trying to dual boot iOS 13.7 and the latest version of iOS 15. I have a A9 device.
> 
> you didn't specify the version, for example, you have to use it like this. ./dualboot.sh --dualboot 13.7

and remember that if you will try again, restorerootfs using --restorerootfs and after that you can dualboot again
