### ISSUE TITLE
Can't switch my device in recovery mode

### ISSUE THREAD

**Issue by iEnderman55** [dualra1n/dualra1n#44]
Hello,  on 14.2!
[*] Switching device into recovery mode...
/home/francy/Scrivania/dualra1n/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/home/francy/Scrivania/dualra1n/binaries/Linux/ideviceenterrecovery: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by dualra1n** [comment]
> Hello, on 14.2! [*] Switching device into recovery mode... /home/francy/Scrivania/dualra1n/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory /home/francy/Scrivania/dualra1n/binaries/Linux/ideviceenterrecovery: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

problems with libssl, sudo apt install libssl openssl
