### ISSUE TITLE
--fixHard doesn't work

### ISSUE THREAD

**Issue by OckoBlox** [dualra1n/dualra1n#46]
Im on Ubuntu and I added --fixHard to the dualboot command however it did not work (the dualboot was succesful but the sounds, microfone, gyroscope and none of the fixHard features worked) iDevice: iPhone 7, iOS 15.7.4, 32gb storage (iPhone9,3), Dualbooted iOS: iOS 14.3

**Comment by OckoBlox** [comment]
log: https://pastebin.com/r3D7LzNX

**Comment by aditya11110** [comment]
I also faced this issue can u do a anti flash recovery format in 3utools of your iphone after that it would fix it

**Comment by OckoBlox** [comment]
Thanks, I will try it :)

**Comment by edwin170** [comment]
that seems like the fixhard arg wasnt correctly

**Comment by edwin170** [comment]
> Thanks, I will try it :)

try this command, --dualboot 14.3 --dont-create-part --fixHard

**Comment by edwin170** [comment]
> I also faced this issue can u do a anti flash recovery format in 3utools of your iphone after that it would fix it

no bro, thats not the issue, that is cause the path doesnt recongnize the argument --fixHard

**Comment by OckoBlox** [comment]
> > Thanks, I will try it :)
> 
> try this command, --dualboot 14.3 --dont-create-part --fixHard

I tried this but when it wanted to back up the preboot folder downra1n just quits.

**Comment by edwin170** [comment]
> 

execute rm -rv prebootBackup/ and execute the command which i send you 
again

**Comment by OckoBlox** [comment]
Ok, will try it

**Comment by edwin170** [comment]
> Ok, will try it

good

**Comment by OckoBlox** [comment]
> > 
> 
> execute rm -rv prebootBackup/ and execute the command which i send you again

It doesn't work

**Comment by dualra1n** [comment]
> > > 
> > 
> > 
> > execute rm -rv prebootBackup/ and execute the command which i send you again
> 
> It doesn't work

wdym, did you do the command again after you remove it ?

**Comment by OckoBlox** [comment]
yes

**Comment by dualra1n** [comment]
> yes

i will check it when i fix it, i will tell you

**Comment by OckoBlox** [comment]
log about it: https://pastebin.com/6A3Ge3XQ

**Comment by dualra1n** [comment]
> log about it: https://pastebin.com/6A3Ge3XQ

bro, its ./dualboot.sh --dualboot 14.3 --dont-create-part --fixHard

**Comment by OckoBlox** [comment]
Oops, very sorry

**Comment by OckoBlox** [comment]
Thanks, now it works and very sorry for that

**Comment by dualra1n** [comment]
> Thanks, now it works and very sorry for that

all right
