### ISSUE TITLE
A small problem

### ISSUE THREAD

**Issue by TYXXFF** [dualra1n/dualra1n#47]
Hello, my friend, I want to ask a question. My iOS device is the iPhone 8plus a11, and the original system is 15.0.1. I want to install 14.3, but the progress is stuck here. I want to ask some solutions, or is my device compatible with dualra1n？
Attached are two images, ubuntu22.10, with Intel processor
![32B013B5-F31C-4D55-92C2-C24CD4773CBF](https://user-images.githubusercontent.com/108198591/229364021-96cde715-1048-4426-9aed-cd7abe50f1a4.jpeg)
![0D9D0265-9628-4B4F-B511-CB5F58D5FF31](https://user-images.githubusercontent.com/108198591/229364026-720e96e2-101e-4da2-a211-2b9c9f8e6e24.jpeg)
I hope to receive your reply as soon as possible
From China，use Google Translate

**Comment by OckoBlox** [comment]
did you disable the password on your iphone?

**Comment by TYXXFF** [comment]
Yes, my main system used palera1n to escape from prison, so I had to cancel the password

**Comment by TYXXFF** [comment]
Yes, my main system used palera1n to escape from prison, so I had to cancel the password

**Comment by OckoBlox** [comment]
then did you add --jail-palera1n into the command

**Comment by TYXXFF** [comment]
Is it necessary to replace -- dualboot 14.3

**Comment by OckoBlox** [comment]
try this command: sudo ./dualboot.sh --dualboot 14.3 --jail-palera1n

**Comment by TYXXFF** [comment]
I'll try. I'm breaking out of jail, Palera1n

**Comment by TYXXFF** [comment]
I'll try. I'm breaking out of jail, Palera1n

**Comment by dualra1n** [comment]
> I'll try. I'm breaking out of jail, Palera1n

first restorerootfs and after that just do the bro said above
