### ISSUE TITLE
MY IPHONE X 10,3 BRICKED IT BOOTLOOPS

### ISSUE THREAD

**Issue by Aditya20110** [dualra1n/dualra1n#48]
DOWNGRADE TO 14.3 IPHONE X 10,3 IOS 16,3 

LOG IS ATTACHED.

https://drive.google.com/file/d/1kOaAt29tL5xKzqRXjyPNLDRoNFCCpzuG/view?usp=share_link

**Comment by dualra1n** [comment]
> DOWNGRADE TO 14.3 IPHONE X 10,3 IOS 16,3 
> 
> 
> 
> LOG IS ATTACHED.
> 
> 
> 
> https://drive.google.com/file/d/1kOaAt29tL5xKzqRXjyPNLDRoNFCCpzuG/view?usp=share_link

Mmm that boot into the second iOS ?

**Comment by aditya11110** [comment]
Bro, i restored it but whats the issue? If you added support for ios 16??

**Comment by edwin170** [comment]
> Bro, i restored it but whats the issue? If you added support for ios 16??

are you trying with a iphone x on ios 16 ?

**Comment by edwin170** [comment]
> Bro, i restored it but whats the issue? If you added support for ios 16??

i think the issues is becuase partition

**Comment by aditya11110** [comment]
> > Bro, i restored it but whats the issue? If you added support for ios 16??
> 
> are you trying with a iphone x on ios 16 ?

Yeah,check out and fix the issue asap please

**Comment by aditya11110** [comment]
I am really working hard to remove every single errors from dualra1n ,downra1n,if you can please add me in contributors

**Comment by edwin170** [comment]
> > > Bro, i restored it but whats the issue? If you added support for ios 16??
> > 
> > 
> > are you trying with a iphone x on ios 16 ?
> 
> Yeah,check out and fix the issue asap please

i am doing it, soon we will have a big update of dualra1n

**Comment by edwin170** [comment]
> I am really working hard to remove every single errors from dualra1n ,downra1n,if you can please add me in contributors

where is the code you write?

**Comment by aditya11110** [comment]
Its still under development

**Comment by aditya11110** [comment]
Im going to show u by tomorrow

**Comment by aditya11110** [comment]
How can i connect with you??

**Comment by edwin170** [comment]
> How can i connect with you??

via discord

**Comment by edwin170** [comment]
> Im going to show u by tomorrow

all right, i will check it and if it's good, I can add it, however, must be useful. please no more English fucking grammar. people just are helping with English but not creating a patcher or a necessary tool, loader-dualra1n its the only thing that i can say that help a lot

**Comment by aditya11110** [comment]
Nono my brother,i dont want to change small grammar its shit… i am studying im just 12 years and i need to study so by tomorrow i will send you the changes.

**Comment by aditya11110** [comment]
But its a request to check out what the shit is happening in ios 16.i think the ssh ramdisk isnt allowed to create partition ,

**Comment by aditya11110** [comment]
Shitty apple

**Comment by edwin170** [comment]
> How can i connect with you??

please try with the branch dev, and tell me if that break the main ios

**Comment by aditya11110** [comment]
> > How can i connect with you??
> 
> please try with the branch dev, and tell me if that break the main ios

check out my gui

**Comment by aditya11110** [comment]
i made downr1n gui please fix issues it is not stable for now but we will make it stable very early! 

https://github.com/aditya11110/Downr1n-gui

just make pull request ,or i will give u write access

**Comment by edwin170** [comment]
very well but i am not git pulling on this proyect

**Comment by aditya11110** [comment]
so can i give u write access??

**Comment by edwin170** [comment]
> so can i give u write access??

lol, i don't want anyone add things to this proyect

**Comment by edwin170** [comment]
> so can i give u write access??

just please try with the dev branch

**Comment by aditya11110** [comment]
why?

**Comment by edwin170** [comment]
> why?

because i tried to fix the problem with iphone x on that branch

**Comment by aditya11110** [comment]
i will try tomorrow

**Comment by edwin170** [comment]
> if u can ,please help with the project of gui,if you can

i will try

**Comment by aditya11110** [comment]
make a pull request so i can give you read write access,

thank you

**Comment by edwin170** [comment]
> make a pull request so i can give you read write access,
> 
> thank you

all right

**Comment by edwin170** [comment]
> i gaved you permission

please try the dev branch

**Comment by aditya11110** [comment]
ok,on your commitment

**Comment by aditya11110** [comment]
im doing it right now

**Comment by aditya11110** [comment]
but its a humble request to help with our gui

**Comment by edwin170** [comment]
> but its a humble request to help with our gui

all right

**Comment by aditya11110** [comment]
still it is not fixed,

**Comment by edwin170** [comment]
> it is still boot looping maybe in ios 16 the ramdisk is not working probably

did the script finish correctly ?

**Comment by edwin170** [comment]
> it is still boot looping maybe in ios 16 the ramdisk is not working probably

are you trying to dualboot with ios 16 to 14 ?

**Comment by Aditya20110** [comment]
> > it is still boot looping maybe in ios 16 the ramdisk is not working probably
> 
> are you trying to dualboot with ios 16 to 14 ?

yes

**Comment by Aditya20110** [comment]
> > it is still boot looping maybe in ios 16 the ramdisk is not working probably
> 
> did the script finish correctly ?

no

**Comment by edwin170** [comment]
> > > it is still boot looping maybe in ios 16 the ramdisk is not working probably
> > 
> > 
> > did the script finish correctly ?
> 
> no

for that reason that dosent finish because this not support ios 16

**Comment by Aditya20110** [comment]
I knew it ,by the way did you checked gui?

**Comment by Aditya20110** [comment]
Im working really hard ,for gui because it will make a lot easier for users

**Comment by Aditya20110** [comment]
?

> > > > it is still boot looping maybe in ios 16 the ramdisk is not working probably
> > > 
> > > 
> > > did the script finish correctly ?
> > 
> > 
> > no
> 
> for that reason that dosent finish because this not support ios 16

?

**Comment by Aditya20110** [comment]
It doesnt works on ios 16
