### ISSUE TITLE
[req] Add seprmvr64 please 

### ISSUE THREAD

**Issue by AppleInternal** [dualra1n/dualra1n#52]
Seprmvr64 will give dualbooting iOS 15 with iOS 13,12 and 11.4.1

**Comment by dualra1n** [comment]
> Seprmvr64 will give dualbooting iOS 15 with iOS 13,12 and 11.4.1

the seprmvr brake the main ios, so that will be a bad idea. also you can dualboot ios 15 to ios 13.6
