### ISSUE TITLE
suck at rsep nonce

### ISSUE THREAD

**Issue by Skye-lol** [dualra1n/dualra1n#56]
the last string of text on ubuntu linux is 

seputil: Gigalocker file (/mnt7/58D4A912-6D57-54AF-9654-6994F2412C72.gl) exists
seputil: Gigalocker initialization completed
sepi digest (20 bytes): 96401c226e90643a86dcf9c6442c9cbf2c58915c
sepi nonce (20 bytes): 50cb8428820a6d1ea61796d164c21ebd05a273b5
rsep digest (20 bytes): 394cb6d184c394db1fcb6acc594260ff156fefd2
rsep nonce (20 bytes): 50cb8428820a6d1ea61796d164c21ebd05a273b5

ive tried everything but idk what to do

**Comment by edwin170** [comment]
> the last string of text on ubuntu linux is
> 
> seputil: Gigalocker file (/mnt7/58D4A912-6D57-54AF-9654-6994F2412C72.gl) exists seputil: Gigalocker initialization completed sepi digest (20 bytes): 96401c226e90643a86dcf9c6442c9cbf2c58915c sepi nonce (20 bytes): 50cb8428820a6d1ea61796d164c21ebd05a273b5 rsep digest (20 bytes): 394cb6d184c394db1fcb6acc594260ff156fefd2 rsep nonce (20 bytes): 50cb8428820a6d1ea61796d164c21ebd05a273b5
> 
> ive tried everything but idk what to do

lol :_. you have that photo on all of your profile ?
