### ISSUE TITLE
--fixHard not working

### ISSUE THREAD

**Issue by AppleInternal** [dualra1n/dualra1n#57]
Device: iPhone 7 (iPhone9,3)
Host OS: MacOS Monterey 12.5.6 (21G531)
Host CPU: AMD Ryzen 5 2600
Device info: Main OS: iOS 15.6, Dualboot OS iOS 13.6, 32 GB edition
Logs after uploading Ramdisk:

[==================================================] 100.0%
+ cd ..
+ '[' -f /Users/enderman/.ssh/known_hosts ']'
+ '[' Darwin = Darwin ']'
+ sed -i.bak /localhost/d /Users/enderman/.ssh/known_hosts
+ sed -i.bak '/127\.0\.0\.1/d' /Users/enderman/.ssh/known_hosts
+ '[' Darwin = Linux ']'
+ /Users/enderman/dualra1n/binaries/Darwin/iproxy 2222 22
+ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
+ echo '[*] Waiting for the ramdisk to finish booting'
[*] Waiting for the ramdisk to finish booting
+ i=1
+ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
+ sleep 1
+ i=2
+ '[' 2 == 15 ']'
+ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
+ sleep 1
+ i=3
+ '[' 3 == 15 ']'
+ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
+ sleep 1
+ i=4
+ '[' 4 == 15 ']'
+ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
+ sleep 1
+ i=5
+ '[' 5 == 15 ']'
+ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
Error connecting to device: No such file or directory
+ sleep 1
+ i=6
+ '[' 6 == 15 ']'
+ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
+ echo 8
8
+ echo '[*] Testing for baseband presence'
[*] Testing for baseband presence
++ remote_cmd '/usr/bin/mgask HasBaseband | grep -E '\''true|false'\'''
++ sleep 1
++ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost '/usr/bin/mgask HasBaseband | grep -E '\''true|false'\'''
++ sleep 1
+ '[' true = true ']'
+ [[ 0x8010 == *\0\x\7\0\0* ]]
++ remote_cmd '/usr/bin/mgask HasBaseband | grep -E '\''true|false'\'''
++ sleep 1
++ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost '/usr/bin/mgask HasBaseband | grep -E '\''true|false'\'''
++ sleep 1
+ '[' true = false ']'
+ '[' '' = 1 ']'
+ echo 8
8
+ dataB=9
+ prebootB=10
+ echo 9
9
+ echo 10
10
+ remote_cmd /usr/bin/mount_filesystems
+ sleep 1
+ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost /usr/bin/mount_filesystems
seputil: Gigalocker file (/mnt7/EBC574DF-3F27-5203-B5EE-5738D70ECD86.gl) exists
seputil: Gigalocker initialization completed
sepi digest (48 bytes): 9f36a585b5ac2cba031410cf8b1a02cbd8204c704d58abc95a64ba001e017fe0aff349ea808254b4eabdd749ed7b0103
sepi nonce (20 bytes): 1345d18ac78524b3665b7df8a856eb7874ebb927
rsep digest (48 bytes): 2b8fc86948a20ff461d135742461cf1674df2ac691241e142140a17c0b88dfe8deb609e8fa99d590c753d0f6cbd11953
rsep nonce (20 bytes): 1345d18ac78524b3665b7df8a856eb7874ebb927
+ sleep 1
++ remote_cmd 'ls /mnt6/active'
+ has_active=/mnt6/active
+ '[' '!' /mnt6/active = /mnt6/active ']'
++ remote_cmd 'cat /mnt6/active'
+ active=44B120DB7761F83B5D0656726CF2701C91A08064098C25A31969E37F2863FAEB584617ED56406D2C9965368DB8890D66
+ mkdir -p boot/iPhone9,3
+ '[' '' = 1 ']'
+ remote_cp root@localhost:/mnt6/44B120DB7761F83B5D0656726CF2701C91A08064098C25A31969E37F2863FAEB584617ED56406D2C9965368DB8890D66/System/Library/Caches/apticket.der blobs/iPhone9,3-13.6.der
+ sleep 1
+ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine scp -r -o StrictHostKeyChecking=no -P2222 root@localhost:/mnt6/44B120DB7761F83B5D0656726CF2701C91A08064098C25A31969E37F2863FAEB584617ED56406D2C9965368DB8890D66/System/Library/Caches/apticket.der blobs/iPhone9,3-13.6.der
+ sleep 1
+ cp -av blobs/iPhone9,3-13.6.der work/IM4M
blobs/iPhone9,3-13.6.der -> work/IM4M
+ '[' '' = 1 ']'

**Comment by edwin170** [comment]
> Device: iPhone 7 (iPhone9,3) Host OS: MacOS Monterey 12.5.6 (21G531) Host CPU: AMD Ryzen 5 2600 Device info: Main OS: iOS 15.6, Dualboot OS iOS 13.6, 32 GB edition Logs after uploading Ramdisk:
> 
> [==================================================] 100.0%
> 
> * cd ..
> * '[' -f /Users/enderman/.ssh/known_hosts ']'
> * '[' Darwin = Darwin ']'
> * sed -i.bak /localhost/d /Users/enderman/.ssh/known_hosts
> * sed -i.bak '/127.0.0.1/d' /Users/enderman/.ssh/known_hosts
> * '[' Darwin = Linux ']'
> * /Users/enderman/dualra1n/binaries/Darwin/iproxy 2222 22
> * /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
> * echo '[_] Waiting for the ramdisk to finish booting'
>   [_] Waiting for the ramdisk to finish booting
> * i=1
> * /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
> * sleep 1
> * i=2
> * '[' 2 == 15 ']'
> * /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
> * sleep 1
> * i=3
> * '[' 3 == 15 ']'
> * /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
> * sleep 1
> * i=4
> * '[' 4 == 15 ']'
> * /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
> * sleep 1
> * i=5
> * '[' 5 == 15 ']'
> * /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
>   Error connecting to device: No such file or directory
> * sleep 1
> * i=6
> * '[' 6 == 15 ']'
> * /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost 'echo connected'
> * echo 8
>   8
> * echo '[_] Testing for baseband presence'
>   [_] Testing for baseband presence
>   ++ remote_cmd '/usr/bin/mgask HasBaseband | grep -E '''true|false''''
>   ++ sleep 1
>   ++ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost '/usr/bin/mgask HasBaseband | grep -E '''true|false''''
>   ++ sleep 1
> * '[' true = true ']'
> * [[ 0x8010 == _\0\x\7\0\0_ ]]
>   ++ remote_cmd '/usr/bin/mgask HasBaseband | grep -E '''true|false''''
>   ++ sleep 1
>   ++ /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost '/usr/bin/mgask HasBaseband | grep -E '''true|false''''
>   ++ sleep 1
> * '[' true = false ']'
> * '[' '' = 1 ']'
> * echo 8
>   8
> * dataB=9
> * prebootB=10
> * echo 9
>   9
> * echo 10
>   10
> * remote_cmd /usr/bin/mount_filesystems
> * sleep 1
> * /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine ssh -o StrictHostKeyChecking=no -p2222 root@localhost /usr/bin/mount_filesystems
>   seputil: Gigalocker file (/mnt7/EBC574DF-3F27-5203-B5EE-5738D70ECD86.gl) exists
>   seputil: Gigalocker initialization completed
>   sepi digest (48 bytes): 9f36a585b5ac2cba031410cf8b1a02cbd8204c704d58abc95a64ba001e017fe0aff349ea808254b4eabdd749ed7b0103
>   sepi nonce (20 bytes): 1345d18ac78524b3665b7df8a856eb7874ebb927
>   rsep digest (48 bytes): 2b8fc86948a20ff461d135742461cf1674df2ac691241e142140a17c0b88dfe8deb609e8fa99d590c753d0f6cbd11953
>   rsep nonce (20 bytes): 1345d18ac78524b3665b7df8a856eb7874ebb927
> * sleep 1
>   ++ remote_cmd 'ls /mnt6/active'
> * has_active=/mnt6/active
> * '[' '!' /mnt6/active = /mnt6/active ']'
>   ++ remote_cmd 'cat /mnt6/active'
> * active=44B120DB7761F83B5D0656726CF2701C91A08064098C25A31969E37F2863FAEB584617ED56406D2C9965368DB8890D66
> * mkdir -p boot/iPhone9,3
> * '[' '' = 1 ']'
> * remote_cp root@localhost:/mnt6/44B120DB7761F83B5D0656726CF2701C91A08064098C25A31969E37F2863FAEB584617ED56406D2C9965368DB8890D66/System/Library/Caches/apticket.der blobs/iPhone9,3-13.6.der
> * sleep 1
> * /Users/enderman/dualra1n/binaries/Darwin/sshpass -p alpine scp -r -o StrictHostKeyChecking=no -P2222 root@localhost:/mnt6/44B120DB7761F83B5D0656726CF2701C91A08064098C25A31969E37F2863FAEB584617ED56406D2C9965368DB8890D66/System/Library/Caches/apticket.der blobs/iPhone9,3-13.6.der
> * sleep 1
> * cp -av blobs/iPhone9,3-13.6.der work/IM4M
>   blobs/iPhone9,3-13.6.der -> work/IM4M
> * '[' '' = 1 ']'

lol you must use it with --dualboot 13.6 --fixHard and if you want to create the files boot again instead to dualboot again, you should add --dont-create-part

**Comment by AppleInternal** [comment]
> lol you must use it with --dualboot 13.6 --fixHard and if you want to create the files boot again instead to dualboot again, you should add --dont-create-part


@edwin170 
[*] Fixing firmwares
mount_apfs: volume could not be mounted: Resource busy
mount_apfs: volume could not be mounted: Resource busy
mount_apfs: volume could not be mounted: Resource busy
seputil: Gigalocker file (/mnt7/EBC574DF-3F27-5203-B5EE-5738D70ECD86.gl) exists
AssertMacros:(value = 0x5),  file: seputil.c, line: 3974
seputil.c: Gigalocker initialization failed: 5
sepi digest (48 bytes): 9f36a585b5ac2cba031410cf8b1a02cbd8204c704d58abc95a64ba001e017fe0aff349ea808254b4eabdd749ed7b0103
sepi nonce (20 bytes): 1345d18ac78524b3665b7df8a856eb7874ebb927
rsep digest (48 bytes): 2b8fc86948a20ff461d135742461cf1674df2ac691241e142140a17c0b88dfe8deb609e8fa99d590c753d0f6cbd11953
rsep nonce (20 bytes): 1345d18ac78524b3665b7df8a856eb7874ebb927
seputil: load fw returned 0xe00002d5
seputil: failed to load /mnt6/44B120DB7761F83B5D0656726CF2701C91A08064098C25A31969E37F2863FAEB584617ED56406D2C9965368DB8890D66/usr/standalone/firmware/sep-firmware.img4 in  mode
mount_apfs: volume could not be mounted: Resource busy
