### ISSUE TITLE
Deepsleep fix uses a lot of power

### ISSUE THREAD

**Issue by Davoped** [dualra1n/dualra1n#60]
Hello author, I am an ipad user and i have a problem with Deepsleep,After using Deepsleep fix or Fiona , although the problem was solved, but when my ipad goes into standby mode,It caused a huge power consumption. Over the course of one night, my ipad's battery dropped from 92 to 68,May I ask if there is any solution,thx!

By the way,My device is ipad mini4 wifi with dual boot ios14.0

**Comment by edwin170** [comment]
> Hello author, I am an ipad user and i have a problem with Deepsleep,After using Deepsleep fix or Fiona , although the problem was solved, but when my ipad goes into standby mode,It caused a huge power consumption. Over the course of one night, my ipad's battery dropped from 92 to 68,May I ask if there is any solution,thx!
> 
> By the way,My device is ipad mini4 wifi with dual boot ios14.0

ufff, that's a big problem bro, autotouch avoid the deepsleep by avoiding that the ipad enter to sleep mode so that mean that must take some battery. sadly i don't have a fix for it yet. if you want try ios 14.8 after that don't install deepsleep or fiona and if the device doesn't have the deepsleep, you got it.

**Comment by edwin170** [comment]
and i am not very sure that dualbooting to ios 14.8 will fix the problem however i think that could

**Comment by Davoped** [comment]
> thanks for your reply,i think i will take some
minitues to try ios14.8.

**Comment by Davoped** [comment]
> and i am not very sure that dualbooting to ios 14.8 will fix the problem however i think that could

I'm sorry to say that even though using ios14.8, I still have the deepsleep bug on my device

**Comment by dualra1n** [comment]
> Hello author, I am an ipad user and i have a problem with Deepsleep,After using Deepsleep fix or Fiona , although the problem was solved, but when my ipad goes into standby mode,It caused a huge power consumption. Over the course of one night, my ipad's battery dropped from 92 to 68,May I ask if there is any solution,thx!
> 
> 
> 
> By the way,My device is ipad mini4 wifi with dual boot ios14.0

Could you please tell me what iPad do you have ?

**Comment by dualra1n** [comment]
Hello bro, here is a mod dualra1n which uses localboot process, this localboot can fix the deep sleep problem so if you want it you can try it https://github.com/edwin170/dualra1n-mod-digital

**Comment by edwin170** [comment]
on A8X device (ipad air 2) and got next results:
downr1n still has deep sleep issue, tested 13.6, 13.6.1, 13.7, 14.1, 14.2, 14,3, 14.8
dualra1n works fine on all ios 14, no issues, but ios 13 still have it, tested 13.6, 13.6.1, 13.7
