### ISSUE TITLE
Accidently restored after dualboot

### ISSUE THREAD

**Issue by ThijsGaming** [dualra1n/dualra1n#62]
I did not know the remove dualboot command existed so i just restored my iphone with finder when something went wrong now im getting this error when trying to dualboot again
![IMG_0001](https://github.com/dualra1n/dualra1n/assets/113776438/c2bc6ee0-935b-4938-b5cf-084990d627c5)

**Comment by dualra1n** [comment]
the only solution that i know for now is that using linux you can jump that error because linux uses another method
