### ISSUE TITLE
[e] cannot open 'ipsw/extracted//Firmware/048-19711-075.dmg.trustcache' Dualboot IOS11 A10

### ISSUE THREAD

**Issue by SERBA2121** [dualra1n/dualra1n#63]
sudo bash dualboot.sh --dualboot 11.4.1 --fixHard --dont-create-part
[*] Command ran: sudo ./dualboot.sh --dualboot 11.4.1 --fixHard --dont-create-part
dualboot | Version mod for ios 13. and 12,11 beta
Written by edwin and some code of palera1n and pyboot:) thanks pelera1n team and seprmvr | thanks for the ramdisk from Nathan | thanks MatthewPierson, Ralph0045, and all people creator of path file boot

[*] Waiting for devices
[11:51:48.589][3] usbmuxd v1.1.1 starting up
[11:51:48.589][3] Using libusb 1.0.25
[11:51:48.593][3] Initialization complete
[*] Detected recovery mode device
[*] Getting device info...
0x8010
d101ap
iPhone9,3
[*] To get into DFU mode, you will be guided through 2 steps:
[*] Press any key when ready for DFU mode
Get ready (0)                                                                                                                         
Release side button, but keep holding volume down (9)                                                                                 
Release side button, but keep holding volume down (6)ERROR: Unable to connect to device                                               
Release side button, but keep holding volume down (2)                                                                                 
[*] Device entered DFU!
extracting ipsw, hang on please ...
Archive:  ipsw/iPhone_4.7_P3_11.0_11.4.1_15G77_Restore.ipsw
'ipsw/extracted//BuildManifest.plist' -> 'work/BuildManifest.plist'
048-19711-075.dmg
[*] Creating ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting ramdisk
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Waiting for the ramdisk to finish booting
bind(): Address in use
Error creating socket for listen port 2222: Address in use
libusb: warning [op_get_configuration] device unconfigured
libusb: error [op_get_active_config_descriptor] device unconfigured
[11:53:17.731][3] Could not get old configuration descriptor for device 2-35: LIBUSB_ERROR_NOT_FOUND
[11:53:17.739][3] Connecting to new device on location 0x20023 as ID 1
[11:53:17.784][3] Connected to v2.0 device 1 on location 0x20023 with serial number ramdisk tool Sep 18 2022 20:14:43
[11:53:17.785][2] device_control_input: Got unhandled payload type 5
[11:53:17.785][2] device_control_input: Got unhandled payload type 5
[11:53:18.522][2] device_control_input: Got unhandled payload type 5
8
[*] Testing for baseband presence
8
9
10
seputil: Gigalocker file (/mnt7/CE457C94-1FB4-519C-96BA-BFEE51341A2F.gl) exists
seputil: Gigalocker initialization completed
sepi digest (48 bytes): b8eeb54b5a1888e412ad3ebfc38cf822647aae016103512b9bf0d1950624570ee961e702d5b5528be01545f5c899c53d
sepi nonce (20 bytes): bba0e7bf104ab7c6a1b88e227a3755a70b776131
rsep digest (48 bytes): d88e2a136a5e23ecaaa380cd7a4198b775bd5c50d2d0fcb6984b2ac5278ec769ecbe8ed33b419db3d64379074987408a
rsep nonce (20 bytes): bba0e7bf104ab7c6a1b88e227a3755a70b776131
'blobs/iPhone9,3-11.4.1.der' -> 'work/IM4M'
[*] Starting step 2
[*] Fixing firmwares
AOP FOUND
aopf
StaticTrustCache FOUND
[e] cannot open 'ipsw/extracted//Firmware/048-19711-075.dmg.trustcache'

**Comment by dualra1n** [comment]
git pull

**Comment by SERBA2121** [comment]
> git pull

this command must be entered in the dualra1n folder?

**Comment by SERBA2121** [comment]
I will be able to install IOS11 or 12 through your script?

**Comment by SERBA2121** [comment]
I was blocked, so I don't have access to information

**Comment by SERBA2121** [comment]
I was blocked, so I don't have access to information
