### ISSUE TITLE
main os 13.5.1 stuck when trying to dualboot ios 15 or 14 and can't resorerootfs

### ISSUE THREAD

**Issue by Sc0vtshy** [dualra1n/dualra1n#67]
[*] Waiting for the ramdisk to finish booting
Error connecting to device: No such file or directory
8
[*] Testing for baseband presence
8
9
10
seputil: Gigalocker file (/mnt7/4DAAF316-8FA3-5515-B631-E4B491E4A1BD.gl) exists
seputil: Gigalocker initialization completed
sepi digest (20 bytes): 0fe1b7c487a0e89d7b4994bc7407cd97e5ed07eb
sepi nonce (20 bytes): 4a535f1bdd4aec9c75460a067a4ee421474a5638
rsep digest (20 bytes): 48bea09d389b14dc9ce301d28a38aa71233af6c2
rsep nonce (20 bytes): 4a535f1bdd4aec9c75460a067a4ee421474a5638

**Comment by edwin170** [comment]
> [_] Waiting for the ramdisk to finish booting Error connecting to device: No such file or directory 8 [_] Testing for baseband presence 8 9 10 seputil: Gigalocker file (/mnt7/4DAAF316-8FA3-5515-B631-E4B491E4A1BD.gl) exists seputil: Gigalocker initialization completed sepi digest (20 bytes): 0fe1b7c487a0e89d7b4994bc7407cd97e5ed07eb sepi nonce (20 bytes): 4a535f1bdd4aec9c75460a067a4ee421474a5638 rsep digest (20 bytes): 48bea09d389b14dc9ce301d28a38aa71233af6c2 rsep nonce (20 bytes): 4a535f1bdd4aec9c75460a067a4ee421474a5638

aaah the sep is not compatible iirc, also dualra1n was created to dualboot ios 15 with ios 14 and 13, but never have tried to dualboot from ios 13.5 as a main to ios 15 or 14. so it's normal that happens, and it looks like that the ramdisk can't load the sep well, so you could open the dualboot.sh file and edit the ./sshrd.sh 15.6 to ./sshrd.sh 13.5

**Comment by Sc0vtshy** [comment]
Love You Brother <3 it worked

**Comment by dualra1n** [comment]
> Love You Brother <3 it worked

wow great

**Comment by dualra1n** [comment]
> Love You Brother <3 it worked 

What! Did you really get dualboot iOS 15 with iOS 13 as a main iOS ?
