### ISSUE TITLE
Shsh error

### ISSUE THREAD

**Issue by Sc0vtshy** [dualra1n/dualra1n#69]
[last.log](https://github.com/dualra1n/dualra1n/files/11832747/last.log)

**Comment by dualra1n** [comment]
look at very weird error, create the active file and put the directory uuid which is on /mnt6/.

**Comment by Sc0vtshy** [comment]
how to do this ?

**Comment by dualra1n** [comment]
> how to do this ?

never mind. just retore the device using itunes or another thing.

**Comment by Sc0vtshy** [comment]
so if i used succesion to restore and reuse dualr1an it should work fine or what ?

**Comment by dualra1n** [comment]
> last.log

idk

**Comment by Sc0vtshy** [comment]
i loved how honest and helpful you are brother ❤️ thanks a lot i appreciate it 👍 and i 'll give it a shot 👌

**Comment by dualra1n** [comment]
> i loved how honest and helpful you are brother ❤️ thanks a lot i appreciate it 👍 and i 'll give it a shot 👌

glad to help you bro 👌, god help you ❤️

**Comment by Sc0vtshy** [comment]
u too ❤️
