### ISSUE TITLE
Question about downgrading

### ISSUE THREAD

**Issue by aqua96** [dualra1n/dualra1n#70]
After i successfully dualboot my device with iOS 14 or 13, is it possible to transform this dualboot into a tethered downgrade by using this tool? (basically delete the main OS so we can use more space into the tethered/dualbooted OS)

The reason I'm asking this is because downr1n doesn't seem to be as stable as dualra1n and it doesn't have iOS 13 support. And it's also not being worked on.

**Comment by dualra1n** [comment]
> After i successfully dualboot my device with iOS 14 or 13, is it possible to transform this dualboot into a tethered downgrade by using this tool? (basically delete the main OS so we can use more space into the tethered/dualbooted OS)
> 
> The reason I'm asking this is because downr1n doesn't seem to be as stable as dualra1n and it doesn't have iOS 13 support. And it's also not being worked on.

well it's a little complicated but you can delete the main ios, just boot ./sshrd.sh boot and when it boot try to connect to it using ssh, when you got that execute "/sbin/apfs_deletefs disk0s1s1 disk0s1s2" if it didn't work try with "/sbin/apfs_deletefs disk0s1s1 || /sbin/apfs_deletefs disk0s1s2". good luck

**Comment by dualra1n** [comment]
> after using ./sshrd.sh boot while in DFU, i booted into the ramdisk or something like than. the phone was connected on the computer, but when i tried to do iproxy 2222 22 and then open another terminal and type ssh -p 2222 root@localhost, it would tell me this: kex_exchange_identification: Connection closed by remote host Connection closed by 127.0.0.1 port 2222

if you are on linux, you must run getsshonlinux script

**Comment by aqua96** [comment]
i did
