### ISSUE TITLE
5 minutes of work

### ISSUE THREAD

**Issue by AppleInternal** [dualra1n/dualra1n#71]
Device: iPhoneX (D221AP. iPhone10,6)
OS from dualbooting: iOS 15.1
OS for dualbooting: iOS 14.3

Device is working 5 minutes normally and then happens turn of (Turning on with force reboot)

**Comment by edwin170** [comment]
> Device: iPhoneX (D221AP. iPhone10,6) OS from dualbooting: iOS 15.1 OS for dualbooting: iOS 14.3
> 
> Device is working 5 minutes normally and then happens turn of (Turning on with force reboot)

deepsleep issues, try to install fiona tweak or use the fix deepsleep option on the dualra1n-loader

**Comment by AppleInternal** [comment]
> > Device: iPhoneX (D221AP. iPhone10,6) OS from dualbooting: iOS 15.1 OS for dualbooting: iOS 14.3
> > Device is working 5 minutes normally and then happens turn of (Turning on with force reboot)
> 
> deepsleep issues, try to install fiona tweak or use the fix deepsleep option on the dualra1n-loader

But device is turn offs when screen is on

**Comment by dualra1n** [comment]
> > > Device: iPhoneX (D221AP. iPhone10,6) OS from dualbooting: iOS 15.1 OS for dualbooting: iOS 14.3
> > > Device is working 5 minutes normally and then happens turn of (Turning on with force reboot)
> > 
> > 
> > deepsleep issues, try to install fiona tweak or use the fix deepsleep option on the dualra1n-loader
> 
> But device is turn offs when screen is on

so it should be a problem with jailbreak, try to open dualra1n and click in the option named restorerootfs. after that --jailbreak again
