### ISSUE TITLE
ideviceenterrecovery dosen't work 

### ISSUE THREAD

**Issue by iEnderman55** [dualra1n/dualra1n#72]
![Screenshot from 2023-07-16 17-02-06](https://github.com/dualra1n/dualra1n/assets/110713827/a489186a-4d4b-4b5a-a18c-46ddd436914c)

Using this command:
![Screenshot from 2023-07-16 17-02-43](https://github.com/dualra1n/dualra1n/assets/110713827/d576261b-7541-431b-ad60-a611a9073cb3)
I've this error also if I write sudo apt update

**Comment by edwin170** [comment]
sudo apt install libssl1.1

**Comment by iEnderman55** [comment]
![Screenshot from 2023-07-17 22-40-29](https://github.com/dualra1n/dualra1n/assets/110713827/1efc97c3-708e-4645-b95b-46daa395bd50)

**Comment by dualra1n** [comment]
skill issue
