### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by iEnderman55** [dualra1n/dualra1n#73]
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 15 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c3ecc : 000080d2
applying patch=0x1800c3f14 : 000080d2
applying patch=0x1800c5b04 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 15 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1 ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c3ecc : 000080d2
applying patch=0x1800c3f14 : 000080d2
applying patch=0x1800b1f64 : 000080d2c0035fd6
applying patch=0x1800b1fbc : 000080d2c0035fd6
applying patch=0x1800eeb30 : 000080d2c0035fd6
applying patch=0x1800c5b04 : 200080d2
applying patch=0x1800c7068 : 58060b50
applying patch=0x1800dd132 : 72643d6d64302064656275673d30783230313465202d76207764743d2d312000
applying patch=0x1800cb3c8 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8020 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x9a7061
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x10bcc64
get_amfi_out_of_my_way_patch: Patching AMFI at 0x10b82a8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
Reading work/ramdisk.dmg...
IM4P outputted to: work/ramdisk.im4p
Reading work/ramdisk.im4p...
Reading work/IM4M...
Creating Image4...
Image4 file outputted to: sshramdisk/ramdisk.img4
none
[*] Booting ramdisk
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Waiting for the ramdisk to finish booting
libusb: warning [op_get_configuration] device unconfigured
libusb: error [op_get_active_config_descriptor] device unconfigured
[13:30:47.815][3] Could not get old configuration descriptor for device 2-14: LIBUSB_ERROR_NOT_FOUND
[13:30:47.819][3] Connecting to new device on location 0x2000e as ID 1
[13:30:47.920][3] Connected to v2.0 device 1 on location 0x2000e with serial number ramdisk tool Sep 18 2022 20:14:43
[13:30:47.921][2] device_control_input: Got unhandled payload type 5
[13:30:48.008][2] device_control_input: Got unhandled payload type 5
Error connecting to device: No error information
8
[*] Testing for baseband presence
7
8
9
seputil: Gigalocker file (/mnt7/D93C2246-3BEE-53F9-8546-EC66A02BE0C0.gl) exists
seputil: Gigalocker initialization completed
sepi digest (48 bytes): 8b10b8e5b66ed27bc449d9923a4aca57e2c49cccbc2e85bb15f827ca7d77f171cd00341528ad1f3519faf9e041302255
sepi nonce (20 bytes): 0cae5a2c2c152063b005d7cf35d4562e279f5aef
rsep digest (48 bytes): f7deb217718e7422fd14a484e0dfd2d6a5517546094c90834489ee320eeccdb79d85567fd5d5f3da2ed766a5c91d8c03
rsep nonce (20 bytes): 0cae5a2c2c152063b005d7cf35d4562e279f5aef
[13:31:07.511][3] Removed device 1 on location 0x2000e
Connection to localhost closed by remote host.

In the screen of the iPad there's wrote: please go to https://panic.apple.com to report this panic

**Comment by edwin170** [comment]
ios 16 ?

**Comment by iEnderman55** [comment]
Yes

**Comment by dualra1n** [comment]
> Yes

that's great bro, you got bootloop your ipad, you are very cool
