### ISSUE TITLE
Would it support iOS 13.7 (main) to dual boot newer version of iOS officially?

### ISSUE THREAD

**Issue by i1itione** [dualra1n/dualra1n#76]
I've seen in issues and it seems that dualra1n is able to support iOS 13 as main OS to dual boot newer iOS. I think it is very useful for avoding upgrade iOS directly when we have checkm8 devices with older iOS version due to downgrade seems worse than dual boot.

**Comment by edwin170** [comment]
> I've seen in issues and it seems that dualra1n is able to support iOS 13 as main OS to dual boot newer iOS. I think it is very useful for avoding upgrade iOS directly when we have checkm8 devices with older iOS version due to downgrade seems worse than dual boot.

yeah, that could be a good idea but ios 13 doesn't have preboot partition and it seems like we can't create the preboot partition if our main ios is 13 however i guess we can use a apfs.util from ios 14.3 and maybe that can work, also there is a tool named ramiel and divise which is a dualboot for ios 13.7 and it work well. if you want to dualboot try to dualboot with divise to ios 14.3 and when you success and you get reboot so then use dualra1n normal branch to create the boot files --dualboot 14.3 --dont-create-part and it will boot the second ios iirc. if it doesn't work try with ramiel

**Comment by dualra1n** [comment]
> When I tried using divise on my iPad Pro 12.9 (2nd Gen.) running iOS 13.7, I can't choose any version of iOS 14 to download, then I found this info from divise 1.2.1 chagelog: "iOS 14 main support (iOS 13 main and 14 second is NOT supported).", therefore I can't try this method.

mmh so if divise can't dual boot as iOS 14 as main it probably will need much work to adapt dual boot for iOS 13.7. also I don't know if Ramdisk work on that versions
