### ISSUE TITLE
[*] Patching kernel ... RuntimeError: pyliblzfse not installed, cannot use LZFSE compression

### ISSUE THREAD

**Issue by chenfanfang** [dualra1n/dualra1n#78]
*** Unmounting...
nx_volume_group_update:7756: disk0s1s8 Volume SystemB role 200 Not a System or data volume
sanity_check_alloced_blocks:805: disk0s1s8 fs_alloc_count mismatch: fs root nodes 1 extent 1 omap 405 snap_meta 1 doc_id 0 prev_doc_id 0 fext: 0 pfkur: 0 er: 0 udata: 1546174 fs_alloc_count 1592139 != count 1546583
dev_dump:256: Aggregate destructed: dev=0x106604130 di=0 dv_num_slice=53 dv_num_slice_blk=589824 dv_num_lslice_blk=579141

*** Success!
[*] Copying var ...
var was copied
[*] Copying preboot ...
[*] installing trollstore
[*] Saving snapshot
[*] Adding the kernel to preboot
krnl
[*] Step 1 is complete. You can use the --dont-create-part option to avoid copying and creating partitions, along with redoing any necessary configurations if needed.
[*] Starting step 2
[*] Fixing firmwares
AOP FOUND
aopf
StaticTrustCache FOUND
trst
Homer FOUND
homr
AVE FOUND
uh
[*] Fixed firmware suscessfully
IOS 14 or 15 dualboot detected, we are gonna use localboot boot process
[*] Adding new boot images: kernelcache, root_hash, StaticTrustCache, devicetree...
[*] Copying the new boot images to work with
dtre
[*] Patching kernel ...
RuntimeError: pyliblzfse not installed, cannot use LZFSE compression
chenfanngdembp2:dualra1n chenfanfang$

**Comment by chenfanfang** [comment]
iphone 7
ios 15.7.8 

help me please

**Comment by chenfanfang** [comment]
install iOS 14.2

**Comment by dualra1n** [comment]
Use python 3.8 preferible

**Comment by DB-UA-DE** [comment]
You have to install pyliblzfse with "pip install pyliblzfse" or "pip3 install pyliblzfse" command.
