### ISSUE TITLE
mount_apfs: volume could not be mounted: No such file or directory

### ISSUE THREAD

**Issue by DB-UA-DE** [dualra1n/dualra1n#79]
Device: iPhone 7 (GSM)
Host iOS: iOS 15.7.7
Target iOS: iOS 13.7

Log:
[*] Waiting for devices
[*] Detected normal mode device
Hello, iPhone9,3 on 13.7!
[*] Switching device into recovery mode...
Telling device with udid ae2a94390d29a350b731004e0afe7c335e5f3121 to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device in recovery mode
[*] Getting device info...
0x8010
d101ap
iPhone9,3
[*] To get into DFU mode, you will be guided through 2 steps:
[*] Press any key when ready for DFU mode
Get ready (0)
Release side button, but keep holding volume down (9)
Release side button, but keep holding volume down (2)
[*] Device entered DFU!
extracting ipsw, hang on please ...
Archive:  ipsw/iPhone_4.7_P3_13.7_17H35_Restore.ipsw
ipsw/extracted//BuildManifest.plist -> work/BuildManifest.plist
[*] Creating ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting ramdisk
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
bind(): Address already in use
Error creating socket for listen port 2222: Address already in use
[*] Waiting for the ramdisk to finish booting
8
[*] Testing for baseband presence
9
10
11
seputil: Gigalocker file (/mnt7/1567AD52-4DA8-5631-B8B3-E174AEBE0E4B.gl) exists
seputil: Gigalocker initialization completed
sepi digest (48 bytes): 6cd78b731e8b1477a59d42c31620bca9d4690ebbe2b0749beaa4bce6c013cf8497a8451ece840b98f0a5b7a285e87fb7
sepi nonce (20 bytes): 5e19485a4450f8d39a7fe31f88879ced460a70b8
rsep digest (48 bytes): 3bd977b45548330b94b9ce693f08911e29be962cfa213e6307ebd2075ecc6d02f615ac00b0f4bb0c9904d658994f26de
rsep nonce (20 bytes): 5e19485a4450f8d39a7fe31f88879ced460a70b8
[*] backup preboot partition... please dont delete directory prebootBackup
blobs/iPhone9,3-13.7.der -> work/IM4M
[*] Starting step 1
[*] Verifying if we can continue with the dualboot
ls: /dev/disk0s1s9: No such file or directory
[* ]Sucessfull verified
[*] Creating partitions
[*] partitions created, continuing...
[*] Partitions are already created
[* ]Mounting filesystems 
mount_apfs: volume could not be mounted: No such file or directory

I get this error only with my iPhone 7, iPhone SE works fine.
I don't know exactly how to fix it so I think maybe the developer will answer.

**Comment by dualra1n** [comment]
backup preboot partition... please dont delete directory prebootBackup, lol you have a very old version of dualra1n iirc, execute git pull, and then execute --restorerootfs and try dualboot again

**Comment by DB-UA-DE** [comment]
It's already up to date, maybe it's because of not updated ios13 branch, will try with iOS 14.

**Comment by dualra1n** [comment]
> It's already up to date, maybe it's because of not updated ios13 branch, will try with iOS 14.

Yeah probably with iOS 14 it will work, I need to update the main branch to iOS 13 compatible because iOS 13 Branch is very old and with errors

**Comment by DB-UA-DE** [comment]
Yeah, it worked with iOS 14.
