### ISSUE TITLE
Does it support main iOS 15.7.x and dual boot to iOS 15.4.1?

### ISSUE THREAD

**Issue by i1itione** [dualra1n/dualra1n#80]
I have let my iPhone 7 which is running iOS 15.7.8 dual boot to iOS 14.8 successfully, now I have a question, can I dual boot to iOS 15.4.1 (or any iOS 15 but not above 15.4.1)? Because I want to use TrollStore on iOS 15 which existed CT bug version.

**Comment by dualra1n** [comment]
> I have let my iPhone 7 which is running iOS 15.7.8 dual boot to iOS 14.8 successfully, now I have a question, can I dual boot to iOS 15.4.1 (or any iOS 15 but not above 15.4.1)? Because I want to use TrollStore on iOS 15 which existed CT bug version.

Yeah you can
