### ISSUE TITLE
RuntimeError: pyliblzfse not installed, cannot use LZFSE compression

### ISSUE THREAD

**Issue by duyan719** [dualra1n/dualra1n#81]
[*] Fixing firmwares
AOP FOUND
aopf
StaticTrustCache FOUND
trst
Homer FOUND
homr
AVE FOUND
uh
[*] Fixed firmware suscessfully
IOS 14 or 15 dualboot detected, we are gonna use localboot boot process
[*] Adding new boot images: kernelcache, root_hash, StaticTrustCache, devicetree... 
[*] Copying the new boot images to work with
dtre
[*] Patching kernel ...
RuntimeError: pyliblzfse not installed, cannot use LZFSE compression

how to fix it

**Comment by edwin170** [comment]
> [_] Fixing firmwares AOP FOUND aopf StaticTrustCache FOUND trst Homer FOUND homr AVE FOUND uh [_] Fixed firmware suscessfully IOS 14 or 15 dualboot detected, we are gonna use localboot boot process [_] Adding new boot images: kernelcache, root_hash, StaticTrustCache, devicetree... [_] Copying the new boot images to work with dtre [*] Patching kernel ... RuntimeError: pyliblzfse not installed, cannot use LZFSE compression
> 
> how to fix it

git pull and try again
