### ISSUE TITLE
RuntimeError: pyliblzfse not installed, cannot use LZFSE compression

### ISSUE THREAD

**Issue by trandinhgiabao2612** [dualra1n/dualra1n#87]
Yep, I just installed linux mint, just installed some packages but while loading, it shows this error: RuntimeError: pyliblzfse not installed, cannot use LZFSE compression. Anyone how to fix it?

![Picture1](https://github.com/dualra1n/dualra1n/assets/108709755/66c032bc-0c02-468b-a480-7007f15a6217)

**Comment by edwin170** [comment]
in an attempt to simplify for anyone having the issue of SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats, please try the following 3 commands:

sudo pip uninstall lzss
sudo git clone https://github.com/yyogo/pylzss && cd pylzss
sudo python3 setup.py install

and then re-run dualra1n, lol sorry for the delay
