### ISSUE TITLE
Add checkra1n jailbreak option in iOS 14 

### ISSUE THREAD

**Issue by Saad050** [dualra1n/dualra1n#88]
I want to jailbreak iOS 14 with cheackra1n but i am not able to jailbreak with checkra1n after downgrading because device doesn't boot. So, I request you to add checkra1n option for jailbreak or tell me any other way to jailbreak with checkra1n after booting iOS 14 or before booting either one is ok for me.
please reply as soon as possible

**Comment by klutzyT** [comment]
Why do you have to use checkra1n? dualra1n includes a jailbreak in it, if you are just trying to use pongo os go back to iOS 15 and use palera1n-c

**Comment by edwin170** [comment]
> I want to jailbreak iOS 14 with cheackra1n but i am not able to jailbreak with checkra1n after downgrading because device doesn't boot. So, I request you to add checkra1n option for jailbreak or tell me any other way to jailbreak with checkra1n after booting iOS 14 or before booting either one is ok for me.
> please reply as soon as possible

lmao, checkra1n doesn't work with dualra1n sadly
