### ISSUE TITLE
iPhone6s iOS15.8->14.8 ERROR: Unable to connect to device

### ISSUE THREAD

**Issue by Cregin** [dualra1n/dualra1n#93]
download succeeded
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:000002B44E240D2C IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:000002B44E240D2C IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 15 iBoot detected!
getting get_sigcheck_patch() patch
applying patch=0x18038db94 : 000080d2
applying patch=0x18038db50 : 000080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 15 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1 ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x87000d474 : 000080d2
applying patch=0x87000d430 : 000080d2
applying patch=0x870001d28 : 000080d2c0035fd6
applying patch=0x870001d80 : 000080d2c0035fd6
applying patch=0x870031f74 : 000080d2c0035fd6
applying patch=0x87000f038 : 200080d2
applying patch=0x870010658 : 1ad30610
applying patch=0x87001e0b8 : 72643d6d64302064656275673d30783230313465202d76207764743d2d312000
applying patch=0x870014184 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8020 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x973ee1
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x1076c64
get_amfi_out_of_my_way_patch: Patching AMFI at 0x10722a8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
/dev/disk4          	                               	/private/tmp/SSHRD
other/trollstore/ -> /tmp/SSHRD
other/trollstore//usr -> /tmp/SSHRD/usr
other/trollstore//usr/trollstore -> /tmp/SSHRD/usr/trollstore
other/trollstore//usr/trollstore/PersistenceHelper -> /tmp/SSHRD/usr/trollstore/PersistenceHelper
other/trollstore//usr/trollstore/trollstorehelper -> /tmp/SSHRD/usr/trollstore/trollstorehelper
other/trollstore//usr/bin -> /tmp/SSHRD/usr/bin
other/trollstore//usr/bin/trollstoreinstaller -> /tmp/SSHRD/usr/bin/trollstoreinstaller
other/trollstore//usr/bin/rsync -> /tmp/SSHRD/usr/bin/rsync
other/trollstore//etc -> /tmp/SSHRD/etc
other/trollstore//etc/profile.d -> /tmp/SSHRD/etc/profile.d
other/trollstore//etc/profile.d/rsync.sh -> /tmp/SSHRD/etc/profile.d/rsync.sh
"disk4" ejected.
Reading work/ramdisk.dmg...
IM4P outputted to: work/ramdisk.im4p
Reading work/ramdisk.im4p...
Reading work/IM4M...
Creating Image4...
Image4 file outputted to: boot/iPhone8,1/ramdisk.img4
none
[*] Booting the ramdisk
[/] We couldn't get the ipsw curl. we will proceed with -k option with curl
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:000002B44E240D2C IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
ERROR: Unable to connect to device
[-] An error occurred

**Comment by edwin170** [comment]
> download succeeded
> usb_timeout: 5
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:000002B44E240D2C IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
> Found the USB handle.
> Now you can boot untrusted images.
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> Found the USB handle.
> usb_timeout: 5
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:000002B44E240D2C IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
> Found the USB handle.
> Now you can boot untrusted images.
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> Found the USB handle.
> main: Starting...
> iOS 15 iBoot detected!
> getting get_sigcheck_patch() patch
> applying patch=0x18038db94 : 000080d2
> applying patch=0x18038db50 : 000080d2
> main: Writing out patched file to work/iBSS.patched...
> main: Quitting...
> none
> main: Starting...
> iOS 15 iBoot detected!
> getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1 ) patch
> getting get_debug_enabled_patch() patch
> getting get_unlock_nvram_patch() patch
> getting get_sigcheck_patch() patch
> applying patch=0x87000d474 : 000080d2
> applying patch=0x87000d430 : 000080d2
> applying patch=0x870001d28 : 000080d2c0035fd6
> applying patch=0x870001d80 : 000080d2c0035fd6
> applying patch=0x870031f74 : 000080d2c0035fd6
> applying patch=0x87000f038 : 200080d2
> applying patch=0x870010658 : 1ad30610
> applying patch=0x87001e0b8 : 72643d6d64302064656275673d30783230313465202d76207764743d2d312000
> applying patch=0x870014184 : 1f2003d5
> main: Writing out patched file to work/iBEC.patched...
> main: Quitting...
> none
> krnl
> main: Starting...
> Kernel: Adding AMFI_get_out_of_my_way patch...
> get_amfi_out_of_my_way_patch: Entering ...
> get_amfi_out_of_my_way_patch: Kernel-8020 inputted
> get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x973ee1
> get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x1076c64
> get_amfi_out_of_my_way_patch: Patching AMFI at 0x10722a8
> main: Writing out patched file to work/kcache.patched...
> main: Quitting...
> krnl
> dtre
> rtsc
> rdsk
> /dev/disk4 /private/tmp/SSHRD
> other/trollstore/ -> /tmp/SSHRD
> other/trollstore//usr -> /tmp/SSHRD/usr
> other/trollstore//usr/trollstore -> /tmp/SSHRD/usr/trollstore
> other/trollstore//usr/trollstore/PersistenceHelper -> /tmp/SSHRD/usr/trollstore/PersistenceHelper
> other/trollstore//usr/trollstore/trollstorehelper -> /tmp/SSHRD/usr/trollstore/trollstorehelper
> other/trollstore//usr/bin -> /tmp/SSHRD/usr/bin
> other/trollstore//usr/bin/trollstoreinstaller -> /tmp/SSHRD/usr/bin/trollstoreinstaller
> other/trollstore//usr/bin/rsync -> /tmp/SSHRD/usr/bin/rsync
> other/trollstore//etc -> /tmp/SSHRD/etc
> other/trollstore//etc/profile.d -> /tmp/SSHRD/etc/profile.d
> other/trollstore//etc/profile.d/rsync.sh -> /tmp/SSHRD/etc/profile.d/rsync.sh
> "disk4" ejected.
> Reading work/ramdisk.dmg...
> IM4P outputted to: work/ramdisk.im4p
> Reading work/ramdisk.im4p...
> Reading work/IM4M...
> Creating Image4...
> Image4 file outputted to: boot/iPhone8,1/ramdisk.img4
> none
> [*] Booting the ramdisk
> [/] We couldn't get the ipsw curl. we will proceed with -k option with curl
> usb_timeout: 5
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:000002B44E240D2C IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
> Found the USB handle.
> Now you can boot untrusted images.
> usb_timeout: 5
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> Found the USB handle.
> [==================================================] 100.0%
> [==================================================] 100.0%
> ERROR: Unable to connect to device
> [-] An error occurred

mmh check usb

**Comment by bobbyl140** [comment]
@edwin170 I'm having this issue, iPad mini 4, it goes into DFU and then breaks right before booting.

`./dualboot.sh --downgrade 14.8`
```
[*] Command ran: ./dualboot.sh --downgrade
<string>:1: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
<string>:1: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
dualboot | Version: 8.5
Created by edwin :) | Some functions code from palera1n.sh, Thanks Nathan for the ramdisks | thanks MatthewPierson, Ralph0045, and to all of the creaters of path file boot

[*] Looking for devices
[*] Detected normal mode device
iPad5,1 connected on 14.8!
[*] Switching device into recovery mode...
Telling device with udid 959e33ec67746816a7578975e43f4572290c33b9 to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device in recovery mode
[*] Getting your device info...
[*] Detected cpid, your cpid is 0x7000
[*] Detected model, your model is j96ap
[*] Detected deviceid, your deviceid is iPad5,1
[*] To get into DFU mode, you will be guided through 2 steps:
[*] Press any key when ready for DFU mode
Get ready (0)
Release power button, but keep holding home button (9)
Release power button, but keep holding home button (3)
[*] Your device has entered DFU!
[?] Found matching IPSW: ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
[?] Do you want to use it? Please write 'yes' or 'no'
yes
[*] Selected IPSW: ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
[*] Checking if the ipsw is for your device
[*] Checking ipsw version
[*] Extracting ipsw, this could take a while...
Archive:  ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
[*] Creating the ramdisk
<string>:1: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
[-] Ramdisk is already created so SKIPPING ...
[*] Booting the ramdisk
<string>:1: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
[/] We couldn't get the ipsw curl. we will proceed with -k option with curl
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0004102224320226 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0004102224320226 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0004102224320226 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0004102224320226 IBFL:1C SRTG:[iBoot-1992.0.0.1.19] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
ERROR: Unable to connect to device
[-] An error occurred
```

**Comment by dualra1n** [comment]
> @edwin170 I'm having this issue, iPad mini 4, it goes into DFU and then breaks right before booting.
> 
> 
> 
> `./dualboot.sh --downgrade 14.8`
> 
> ```
> 
> [*] Command ran: ./dualboot.sh --downgrade
> 
> <string>:1: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
> 
> <string>:1: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
> 
> dualboot | Version: 8.5
> 
> Created by edwin :) | Some functions code from palera1n.sh, Thanks Nathan for the ramdisks | thanks MatthewPierson, Ralph0045, and to all of the creaters of path file boot
> 
> 
> 
> [*] Looking for devices
> 
> [*] Detected normal mode device
> 
> iPad5,1 connected on 14.8!
> 
> [*] Switching device into recovery mode...
> 
> Telling device with udid 959e33ec67746816a7578975e43f4572290c33b9 to enter recovery mode.
> 
> Device is successfully switching to recovery mode.
> 
> [*] Waiting for device in recovery mode
> 
> [*] Getting your device info...
> 
> [*] Detected cpid, your cpid is 0x7000
> 
> [*] Detected model, your model is j96ap
> 
> [*] Detected deviceid, your deviceid is iPad5,1
> 
> [*] To get into DFU mode, you will be guided through 2 steps:
> 
> [*] Press any key when ready for DFU mode
> 
> Get ready (0)
> 
> Release power button, but keep holding home button (9)
> 
> Release power button, but keep holding home button (3)
> 
> [*] Your device has entered DFU!
> 
> [?] Found matching IPSW: ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
> 
> [?] Do you want to use it? Please write 'yes' or 'no'
> 
> yes
> 
> [*] Selected IPSW: ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
> 
> [*] Checking if the ipsw is for your device
> 
> [*] Checking ipsw version
> 
> [*] Extracting ipsw, this could take a while...
> 
> Archive:  ipsw/iPad_64bit_TouchID_14.8_18H17_Restore.ipsw
> 
> [*] Creating the ramdisk
> 
> <string>:1: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
> 
> [-] Ramdisk is already created so SKIPPING ...
> 
> [*] Booting the ramdisk
> 
> <string>:1: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
> 
> [/] We couldn't get the ipsw curl. we will proceed with -k option with curl
> 
> usb_timeout: 5
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0004102224320226 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
> 
> Found the USB handle.
> 
> Stage: RESET
> 
> ret: true
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0004102224320226 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
> 
> Found the USB handle.
> 
> Stage: SETUP
> 
> ret: true
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0004102224320226 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
> 
> Found the USB handle.
> 
> Stage: PATCH
> 
> ret: true
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:0004102224320226 IBFL:1C SRTG:[iBoot-1992.0.0.1.19] PWND:[gaster]
> 
> Found the USB handle.
> 
> Now you can boot untrusted images.
> 
> usb_timeout: 5
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> Found the USB handle.
> 
> [==================================================] 100.0%
> 
> [==================================================] 100.0%
> 
> ERROR: Unable to connect to device
> 
> [-] An error occurred
> 
> ```

Try cd ramdisk/ then git pull then cd .. then try downr1n again

**Comment by bobbyl140** [comment]
The same thing happens after running those unfortunately.

**Comment by dualra1n** [comment]
> The same thing happens after running those unfortunately.

Try rm -rfv ramdisk/

**Comment by bobbyl140** [comment]
That time it downloaded the ramdisk and some other stuff, but the same error happened at the end.

**Comment by dualra1n** [comment]
@Ldrsnow could you help please? it is an A8 0x7000

**Comment by Lrdsnow** [comment]
this is the one i just added more sleeps and it fixed the issue

**Comment by bradycodemaster** [comment]
https://github.com/y08wilm/Semaphorin has this problem to @y08wilm
