### ISSUE TITLE
Does it support main iOS 14 and dual boot to iOS 15?

### ISSUE THREAD

**Issue by CharaMac** [dualra1n/dualra1n#94]
I have let my iPhone X which is running iOS 14.8 dual boot to iOS 14.3 successfully, now I have a question, can I dual boot to iOS 15.4.1 (or any iOS 15 but not above 15.4.1)? Because I want to try iOS 15.

**Comment by CharaMac** [comment]
I think is impossible, because the SEP and BB is iOS 14's, iOS 15 may not support it.

**Comment by edwin170** [comment]
> I have let my iPhone X which is running iOS 14.8 dual boot to iOS 14.3 successfully, now I have a question, can I dual boot to iOS 15.4.1 (or any iOS 15 but not above 15.4.1)? Because I want to try iOS 15.

lol it worked dual booting iOS 14 with iOS 14, well yes, you can dual boot to iOS 15 being on iOS 14 iirc, I saw some people being on iOS 14 and dual booting to iOS 15. you should use for example: ./dualboot.sh --dualboot 15.5 --bootx. then to boot ./dualboot.sh --boot 15.5 --bootx. to jailbreak use --jailbreak 15.5 --bootx. remember always use --bootx
