### ISSUE TITLE
Says a code should be displayed on iphone if not use --boot

### ISSUE THREAD

**Issue by herefor-vega8** [dualra1n/dualra1n#95]
Hi,
at the end it shows a code should be displayed on iphone or use --boot.
I used --boot when it did not show the code.
It doesnt work and boots again to recovery.
Using iphone 6s and dualbooting to ios 14.1.
Thanks

**Comment by edwin170** [comment]
> Hi,
> at the end it shows a code should be displayed on iphone or use --boot.
> I used --boot when it did not show the code.
> It doesnt work and boots again to recovery.
> Using iphone 6s and dualbooting to ios 14.1.
> Thanks

yeah somehow dualra1n is broken sadly, when I fix it I tell you

**Comment by edwin170** [comment]
> Hi,
> 
> at the end it shows a code should be displayed on iphone or use --boot.
> 
> I used --boot when it did not show the code.
> 
> It doesnt work and boots again to recovery.
> 
> Using iphone 6s and dualbooting to ios 14.1.
> 
> Thanks

I found a solution and is this, execute in the terminal 


sudo python3 -m pip uninstall lzss pylzss

sudo git clone https://github.com/yyogo/pylzss && cd pylzss

git checkout 8efcda0

sudo python3 setup.py install

and then re-run dualra1n or downr1n

**Comment by herefor-vega8** [comment]
Shows the same error.

**Comment by edwin170** [comment]
> Shows the same error.

execute sudo python3 -m pip uninstall lzss pylzss
, and then try downr1n again

**Comment by herefor-vega8** [comment]
Still no success. Shows the same error.

**Comment by edwin170** [comment]
ok give up then

**Comment by edwin170** [comment]
or send me an image when you execute sudo python3 -m pip uninstall lzss pylzss, so I can see if it is removed well

**Comment by herefor-vega8** [comment]
![Screenshot_2024-02-07_10-04-25](https://github.com/dualra1n/dualra1n/assets/152514683/ada169e4-c2ff-4ed0-8702-24cbcb1342f9)
Its shows pylzss is not installed is it fine?

**Comment by edwin170** [comment]
> ![Screenshot_2024-02-07_10-04-25](https://private-user-images.githubusercontent.com/152514683/302897854-ada169e4-c2ff-4ed0-8702-24cbcb1342f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTczMjgsIm5iZiI6MTcwNzMxNzAyOCwicGF0aCI6Ii8xNTI1MTQ2ODMvMzAyODk3ODU0LWFkYTE2OWU0LWMyZmYtNGVkMC04NzAyLTI0Y2JjYjEzNDJmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxNDQzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjMxMTQ2YmU1ZTExOWRjODM5MTBkYTFlMmUyM2E2MTdmMjQxNjFmMDBlZWVkZWE5ZWVjYWRmZjVlOWE1ZjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M5sbrLaoO3I0lXYPJBb2AiqAHb10mP5Tg5dZDimLmWE)
> Its shows pylzss is not installed is it fine?

yeah it is good, soo it should've worked, please go to discord server to get help easier

**Comment by herefor-vega8** [comment]
So, should I run these and re run dualra1n.
sudo python3 -m pip uninstall lzss pylzss
git checkout 8efcda0

or 

only sudo python3 -m pip uninstall lzss pylzss
this and re-run.

And should I also remove the pylzss from my home folder?

**Comment by edwin170** [comment]
> So, should I run these and re run dualra1n. sudo python3 -m pip uninstall lzss pylzss git checkout 8efcda0
> 
> or
> 
> only sudo python3 -m pip uninstall lzss pylzss this and re-run.
> 
> And should I also remove the pylzss from my home folder?

only sudo python3 -m pip uninstall lzss pylzss
