### ISSUE TITLE
Getting Runtime Error when installing 

### ISSUE THREAD

**Issue by skibidman** [dualra1n/dualra1n#96]
Hi i have a problem every time i try too install dualra1n i get "RuntimeError: pyliblzfse not installed, cannot use LZFSE compression"
i tried reinstalling almost everything i found and still got this error does anybody know how to fix?
![image](https://github.com/dualra1n/dualra1n/assets/158618612/f981aa90-469b-42a5-a0bd-d17f77ab5dbc)

**Comment by edwin170** [comment]
> Hi i have a problem every time i try too install dualra1n i get "RuntimeError: pyliblzfse not installed, cannot use LZFSE compression"
> i tried reinstalling almost everything i found and still got this error does anybody know how to fix?
> ![image](https://private-user-images.githubusercontent.com/158618612/303954501-f981aa90-469b-42a5-a0bd-d17f77ab5dbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2OTQ1NjAsIm5iZiI6MTcwNzY5NDI2MCwicGF0aCI6Ii8xNTg2MTg2MTIvMzAzOTU0NTAxLWY5ODFhYTkwLTQ2OWItNDJhNS1hMGJkLWQxN2Y3N2FiNWRiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQyMzMxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjk3NjhkZjcyMjRjOWJlMDdiMDlkOGExNGIyNzkxMDY5OTAwMDBkZjc1NWFkMmRlNjgyZDk3YTFhMGZjYTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PaW_pOUMdhSNlvTUfb401_ipc2jn2Uq6GLjdWnzNsFA)

python3 -m pip install pyliblzfse

**Comment by edwin170** [comment]
try with sudo too

**Comment by skibidman** [comment]
Already tried Still same error
