### ISSUE TITLE
Unknown error of 'An error occurred'

### ISSUE THREAD

**Issue by luckyyf0517** [dualra1n/dualra1n#99]
...
download succeeded
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:001339E21AD10026 IBFL:1C SRTG:[iBoot-1992.0.0.1.19] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[-] An error occurred

**Comment by xhhxbg** [comment]
The device is ipad mini 4, ios 15.8

**Comment by edwin170** [comment]
problem decrypting firware, sometimes it is fixed by restoring with itunes or other tool
